import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SideNavigation } from "../components/Navigation/SideNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex">
          <div className="min-w-[180px] h-full overflow-auto p-4 bg-indigo-400 text-white">
            <h2 className="text-lg">Componentes</h2>
            <hr /><br />

            <SideNavigation />
          </div>

          <main className="p-4 w-full h-full overflow-auto">
            {children}
          </main>
        </div>

      </body>
    </html>
  );
}
